[build]
build-std = ["core", "std", "alloc", "panic_abort"]

[unstable]
build-std = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "target-cpu=znver3",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "linker-plugin-lto=true",
    "-C", "force-frame-pointers=no",
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
debug-assertions = false
