auto_sync = true
sync_address = "https://api.atuin.sh"
sync_frequency = "5m"
[sync]
records = true
search_mode = "fuzzy"
filter_mode = "global"
workspaces = true
style = "compact"
inline_height = 25
enter_accept = false
exit_mode = "return-original"
show_preview = true
history_format = "{time} {duration} {command}"
invert = false
[theme]
name = "catppuccin-mocha-mauve"